### ISSUE TITLE
Create store info page

### ISSUE THREAD

**Issue by Gily-H** [Gily-H/FoodMaps#4]
Store Page will implement the following functionality

- [ ] Store details (name, address, image, description) - see issue #3 
- [ ] Edit Store info button - see issue #5 
- [ ] Add produce items button - see issue #7 
- [ ] Embedded google map with address location - see issue #8 
- [ ] List of items being sold at store - see issue #6 
- [ ] User comments about the store - see issue #9
